### ISSUE TITLE
Ако правим блог трябва с нещо да е уникален за да не сме скучни :)

### ISSUE THREAD

**Issue by MeLean** [Masovski/TeamDARBY#1]
Според мен трябва нашия блог да се отличава с нещо от другите блогове, тоест да е уникален. Имам еднба идея и искам да почна да работя по нея. Идеята е да се направи страница на която потребителите да задават тема, по която искат да чуят мнението да теам дарби или там на който е блога. Страницата да представлява .php страница с зададени теми от потребителя всяка тема ще си има бутон, които да и задава важност и всеки потребител като цъкне на бутона, темата ще става по важна (нещо като лайка на фейзбука) и ще се изкачава по-нагоре в класирането и ще бъде разизквана по-скоро. Ще бъда радостен ако чуя вашето мнение.

**Comment by Masovski** [comment]
Teamwork project's done.

**Comment by MeLean** [comment]
Better late than never 🗡️
